/**
 * Runtime environment resolution.
 *
 * ── WHY THIS FILE EXISTS ──────────────────────────────────────────────────
 * On Cloudflare Workers, secrets and bindings are NOT on `process.env`, NOT on
 * `globalThis`, and NOT in `import.meta.env` at runtime. They come from
 * `import { env } from 'cloudflare:workers'`.
 *
 * Reading them the wrong way fails SILENTLY and in the worst possible
 * direction: the rate limiter decides KV is unavailable and falls back to a
 * per-isolate map (no real limit), and delivery decides it is unconfigured and
 * returns 503 to every genuine patient enquiry. Both look fine locally.
 *
 * `cloudflare:workers` only resolves inside the Workers runtime, so the import
 * is guarded and falls back to `process.env` for `astro dev` on Node.
 */

type EnvRecord = Record<string, unknown>;

let runtimeEnv: EnvRecord | null = null;
let resolved = false;

async function loadRuntimeEnv(): Promise<EnvRecord | null> {
  if (resolved) return runtimeEnv;
  resolved = true;

  try {
    // Virtual module — only present inside the Workers runtime.
    // `Env` is generated by `wrangler types` and has no index signature, so
    // widen through unknown rather than asserting across incompatible shapes.
    const mod = (await import(/* @vite-ignore */ 'cloudflare:workers')) as unknown as {
      env?: EnvRecord;
    };
    runtimeEnv = mod.env ?? null;
  } catch {
    runtimeEnv = null;
  }

  return runtimeEnv;
}

/** A string secret, or undefined. Checks the Workers env first, then Node. */
export async function getSecret(key: string): Promise<string | undefined> {
  const cf = await loadRuntimeEnv();
  const fromCf = cf?.[key];
  if (typeof fromCf === 'string' && fromCf !== '') return fromCf;

  const fromNode = typeof process !== 'undefined' ? process.env?.[key] : undefined;
  if (typeof fromNode === 'string' && fromNode !== '') return fromNode;

  return undefined;
}

/** A non-string binding (KV namespace, R2 bucket, D1 database), or undefined. */
export async function getBinding<T = unknown>(key: string): Promise<T | undefined> {
  const cf = await loadRuntimeEnv();
  const binding = cf?.[key];
  return binding === undefined || binding === null ? undefined : (binding as T);
}

/** True when running inside the Cloudflare Workers runtime. */
export async function isWorkersRuntime(): Promise<boolean> {
  return (await loadRuntimeEnv()) !== null;
}
