/**
 * The Edit Mode interface in the page's own language.
 *
 * Interface words only — buttons, statuses, confirmations, errors. Nothing
 * here is site or medical content, and nothing is translated automatically:
 * each language is written out. `{name}`-style placeholders are filled by the
 * client with text it already has (a commit, a count, an item's title).
 *
 * Every key must exist in all three languages; a unit test enforces it.
 */
type Dict = Record<string, string | Record<string, string> | string[]>;

const he: Dict = {
  langName: 'עברית',
  close: 'סגירה', save: 'שמירה', cancel: 'ביטול', edit: 'עריכה', closeEdit: 'סגירת העריכה', remove: 'הסרה', delete: 'מחיקה',
  up: 'למעלה', down: 'למטה', upNamed: 'למעלה: {name}', downNamed: 'למטה: {name}', named: '{action}: {name}', grip: 'גרירה',
  published: 'מוצג באתר', hidden: 'מוסתר', publish: 'הצגה באתר', unpublish: 'הסתרה מהאתר',
  warning: 'כל תוכן נשמר במאגר ציבורי, גם תוכן מוסתר. אין להזין מידע על מטופלים, פרטים רפואיים אישיים או סודות.',
  unsavedClose: 'יש שינויים שלא נשמרו. לסגור ולאבד אותם?',
  unsavedSwitch: 'יש שינויים שלא נשמרו. לעבור ולאבד אותם?',
  unsavedReload: 'השינויים שלא נשמרו יאבדו. לטעון מחדש?',
  unsavedRefresh: 'יש שינויים שלא נשמרו. לרענן בכל זאת?',
  loading: 'טוען את התוכן…', saving: 'שומר…',
  nothingToSave: 'אין שינויים לשמירה — הכול כבר שמור.',
  savedTest: 'נשמר (commit {sha}, ענף בדיקה — האתר הציבורי לא משתנה).',
  savedProd: 'נשמר (commit {sha}); עדיין לא פורסם באתר.',
  doneTest: '{what} (commit {sha}, ענף בדיקה).', doneProd: '{what} (commit {sha}); עדיין לא פורסם באתר.',
  noChange: 'אין שינוי לשמירה.',
  updating: 'מעדכן את תצוגת האתר…',
  updated: 'עודכן — הדף נטען מחדש…',
  updatedDirty: 'התצוגה עודכנה. שמרו או בטלו את השינויים הפתוחים ואז רעננו.',
  updatedAfterReload: 'הדף מציג את השינוי האחרון שנשמר.',
  refreshNow: 'רענון הדף',
  updateFailed: 'השינוי נשמר, אך עדכון תצוגת האתר נכשל. אפשר לנסות שוב בשמירה נוספת; אם זה חוזר, יש לפנות למפתח.',
  updateNotConfigured: 'השינוי נשמר. עדכון אוטומטי של התצוגה אינו מוגדר, ולכן הדף יציג אותו לאחר בנייה מחדש.',
  waitingPublish: 'נשמר (commit {sha}). ממתין לפרסום באתר…',
  publishedSite: 'פורסם באתר',
  publishFailed: 'נשמר, אך הפרסום נכשל. האתר מציג את הגרסה הקודמת. יש לפנות למפתח.',
  testMode: 'מצב בדיקה: שמירות לא משנות את האתר הציבורי',
  claim: 'ניסוח אסור לפי כללי הפרסום הרפואי (למשל הבטחת תוצאה או "הכי טוב")',
  moreIssues: 'ייתכן שיש בעיות נוספות; הן יוצגו אחרי תיקון אלה ושמירה חוזרת.',
  reloadLatest: 'טעינה מחדש של התוכן העדכני', refreshSignIn: 'רענון הדף והתחברות',
  itemN: 'פריט {n}', treatmentNamed: 'טיפול "{name}"', questionNamed: 'שאלה "{name}"', field: 'שדה', invalidValue: 'ערך לא תקין.',
  dayLabel: 'יום {day}', timesRequired: '{day}: יש למלא שעת פתיחה ושעת סגירה (או לסמן "סגור").',
  opensAfterCloses: '{day}: שעת הפתיחה חייבת להיות לפני שעת הסגירה.', badTime: '{day}: שעה לא תקינה.', badDay: '{day}: ערך לא תקין.',
  altClaim: 'התיאור ב{lang} מכיל ניסוח אסור לפי כללי הפרסום הרפואי.',
  showAllTexts: 'הצגת כל הטקסטים באתר',
  intro: 'הקדמה', approach: 'גישת המרפאה — שורה לכל נקודה', credentials: 'השכלה והסמכות — רק עובדות מאושרות בכתב',
  year: 'שנה (לא חובה)', removeCredential: 'הסרת ההסמכה', addCredential: 'הוספת הסמכה',
  ownerConfirm: 'אני מאשר/ת שכל הפרטים ששונו כאן נכונים.',
  contactHint: 'שינוי הכתובת כאן מיועד לתיקון ניסוח של אותו מקום. אם המרפאה עברה, יש לעדכן גם את המפה וקישור Waze דרך המפתח.',
  sameLocation: 'אני מאשר/ת שזו אותה כתובת פיזית, והמפה וקישור Waze עדיין נכונים.',
  hoursHint: 'לחלק מהימים עדיין לא הוגדרו שעות, ולכן שעות הפעילות לא מוצגות באתר. יש למלא שעת פתיחה וסגירה לכל יום, או לסמן "סגור ביום זה", ואז לשמור.',
  closedToday: 'סגור ביום זה', opens: 'פתיחה', closes: 'סגירה',
  newTreatment: 'טיפול חדש', addTreatment: '+ הוספת טיפול', editTreatment: 'עריכת הטיפול',
  servicesHint: 'הסדר כאן הוא הסדר באתר. אפשר לגרור טיפול בידית, או להשתמש בכפתורי למעלה/למטה. השינויים נשמרים בלחיצה על "שמירה".',
  deleteItemConfirm: 'למחוק את "{name}"? המחיקה תתבצע בשמירה.', deleteNeedsSave: 'כדי למחוק: יש לשמור קודם את ההסתרה.',
  backToTreatments: '→ חזרה לרשימת הטיפולים', editingTreatment: 'עריכת טיפול: {name}',
  draftHint: 'טיוטה: אפשר לשמור גם כשחלק מהשדות או מהשפות חסרים. כדי להציג באתר, יש למלא את כל השדות בשלוש השפות.',
  slugLabel: 'כתובת העמוד באנגלית (למשל dental-crowns). לא ניתן לשנות לאחר השמירה.', pageAddress: 'כתובת העמוד: ',
  iconLabel: 'סמל', languageLabel: 'שפה', addItem: 'הוספת פריט',
  addQuestion: '+ הוספת שאלה', newQuestion: 'שאלה חדשה', question: 'שאלה', answer: 'תשובה',
  faqHint: 'שאלה חדשה נשמרת כמוסתרת. אפשר לשמור טיוטה גם בלי כל השפות; כדי להציג באתר נדרש נוסח בעברית, ערבית ואנגלית.',
  unsavedOrder: 'שינוי הסדר עדיין לא נשמר, והפעולה הזו תבטל אותו. להמשיך?',
  heic: 'תמונות HEIC של iPhone אינן נתמכות. בחרו את התמונה דרך "תמונות" (היא תומר אוטומטית ל-JPG), או שמרו אותה כ-JPG.',
  notJpgPng: '"{name}" אינו קובץ JPG או PNG.', unreadable: 'לא ניתן לקרוא את "{name}" כתמונה.',
  tooSmall: '"{name}" קטנה מדי ({w}×{h}). נדרשים לפחות {min} פיקסלים בצד הארוך.', tooLargeAfter: '"{name}" גדולה מדי גם לאחר הקטנה.',
  galleryCount: 'התמונות בגלריה ({n})', galleryEmpty: 'עדיין אין תמונות בגלריה. אפשר להוסיף תמונות למעלה.',
  galleryHint: 'תמונה חדשה נשמרת כמוסתרת; מציגים אותה בכפתור "הצגה באתר". הסדר כאן הוא הסדר באתר — גררו בידית או השתמשו בלמעלה/למטה, ואז "שמירת הסדר".',
  orderChanged: 'הסדר השתנה ועדיין לא נשמר.', saveOrder: 'שמירת הסדר', savingOrder: 'שומר את הסדר…', orderSaved: 'הסדר נשמר',
  needsEnglish: 'נדרש אישור תיאור באנגלית', needEnglishFirst: 'יש לשמור קודם תיאור באנגלית', noPreview: 'לא ניתן להציג תצוגה מקדימה',
  editDescription: 'עריכת התיאור', closeDescription: 'סגירת עריכת התיאור', descriptionGroup: 'תיאור התמונה (לקוראי מסך ולגוגל)',
  saveDescription: 'שמירת התיאור', savingDescription: 'שומר תיאור…', descriptionSaved: 'התיאור נשמר',
  photoShown: 'התמונה סומנה להצגה באתר', photoHidden: 'התמונה הוסתרה מהאתר',
  replace: 'החלפת תמונה', replaceConfirm: 'לאשר שבתמונה החדשה אין מטופל, חלק ממטופל או תמונת לפני/אחרי?',
  checkingImage: 'בודק את התמונה…', uploadingReplacement: 'מעלה את התמונה החדשה…', replaced: 'התמונה הוחלפה',
  deletePhotoConfirm: 'למחוק לצמיתות את התמונה "{name}"? ההיסטוריה נשמרת במאגר.', deleting: 'מוחק…', photoDeleted: 'התמונה נמחקה', hideFirst: 'למחיקה יש להסתיר קודם.',
  uploadGroup: 'הוספת תמונות לגלריה', dropHere: 'גררו תמונות לכאן, או', choosePhotos: 'בחירת תמונות',
  uploadHint: 'JPG או PNG, לפחות 1200 פיקסלים בצד הארוך. תמונה גדולה מדי תוקטן אוטומטית.',
  previewOf: 'תצוגה מקדימה: {name}', uploading: 'מעלה…', photoCategory: 'סוג התמונה', descriptionAll: 'תיאור התמונה (נדרש בשלוש השפות)',
  removeFromList: 'הסרה מהרשימה', uploadConfirm: 'אני מאשר/ת שבאף אחת מהתמונות אין מטופל, חלק ממטופל או תמונת לפני/אחרי.',
  uploadOne: 'העלאת תמונה אחת', uploadMany: 'העלאת {n} תמונות', uploadingNofM: 'מעלה תמונה {n} מתוך {m}…', uploadFailed: 'העלאה נכשלה.',
  uploadedOne: 'התמונה הועלתה ונשמרה כמוסתרת (commit {sha}). כדי להציג אותה באתר לחצו "הצגה באתר".',
  uploadedMany: '{n} תמונות הועלו ונשמרו כמוסתרות (commit {sha}). כדי להציג תמונה באתר לחצו "הצגה באתר".',
  uploadedPartial: 'הועלו {n} מתוך {m}. {f} לא הועלו — הסיבה מופיעה ליד כל תמונה.',
  barTexts: 'כל הטקסטים', barTreatments: 'טיפולים', barPhotos: 'תמונות', preview: 'תצוגת מטופל', backToEdit: 'חזרה לעריכה', exit: 'יציאה',
  titles: { copy: 'טקסטים באתר', services: 'טיפולים', doctor: 'אזור הרופא', faq: 'שאלות נפוצות', contact: 'פרטי התקשרות', hours: 'שעות פעילות', photos: 'גלריית תמונות המרפאה' },
  days: ['ראשון', 'שני', 'שלישי', 'רביעי', 'חמישי', 'שישי', 'שבת'],
  doctorParts: { intro: 'הקדמה', approach: 'גישת המרפאה', credentials: 'השכלה והסמכות' },
  copyLabels: {
    'hero.eyebrow': 'שורה קטנה מעל הכותרת הראשית', 'hero.title': 'כותרת ראשית', 'hero.subtitle': 'משפט פתיחה מתחת לכותרת',
    'trust.explanation.title': 'נקודה 1 — כותרת', 'trust.explanation.body': 'נקודה 1 — הסבר', 'trust.languages.title': 'נקודה 2 — כותרת', 'trust.languages.body': 'נקודה 2 — הסבר',
    'trust.availability.title': 'נקודה 3 — כותרת', 'trust.availability.body': 'נקודה 3 — הסבר', 'trust.personal.title': 'נקודה 4 — כותרת', 'trust.personal.body': 'נקודה 4 — הסבר',
    'treatments.title': 'כותרת אזור הטיפולים', 'treatments.intro': 'פתיח אזור הטיפולים', 'doctor.title': 'כותרת אזור הרופא', 'doctor.cta': 'כפתור באזור הרופא', 'faq.title': 'כותרת השאלות הנפוצות',
    'contact.title': 'כותרת עמוד יצירת קשר', 'contact.subtitle': 'פתיח עמוד יצירת קשר', 'location.title': 'כותרת אזור המיקום', 'location.subtitle': 'פתיח אזור המיקום',
    'gallery.eyebrow': 'שורה קטנה מעל כותרת הגלריה', 'gallery.title': 'כותרת הגלריה', 'gallery.intro': 'פתיח הגלריה',
    'action.bookAppointment': 'כפתור קביעת תור', 'action.readMore': 'קישור "קראו עוד"', 'action.allTreatments': 'קישור "כל הטיפולים"',
    'feedback.title': 'כותרת אזור המשוב', 'feedback.body': 'טקסט אזור המשוב', 'feedback.cta': 'כפתור אזור המשוב',
  },
  contactLabels: { landline: 'טלפון קווי (לדוגמה 04-123-4567)', mobile: 'טלפון נייד (לדוגמה 050-123-4567)', email: 'דוא״ל (לא חובה)', postalCode: 'מיקוד', instagram: 'קישור Instagram', facebook: 'קישור Facebook', googleBusiness: 'קישור לפרופיל Google', street: 'רחוב ומספר', locality: 'יישוב', region: 'אזור' },
  categories: { exterior: 'חזית המרפאה', reception: 'קבלה והמתנה', 'treatment-room': 'חדר טיפולים', equipment: 'ציוד', 'doctor-working': 'הרופא בעבודה', team: 'צוות', atmosphere: 'אווירה' },
  icons: { implant: 'שתל', crown: 'כתר', whitening: 'הלבנה', filling: 'סתימה', veneer: 'ציפוי', aligner: 'יישור שיניים', 'root-canal': 'טיפול שורש', extraction: 'עקירה', cleaning: 'ניקוי', emergency: 'חירום', aesthetic: 'אסתטיקה' },
  serviceFields: { title: 'שם הטיפול (כותרת העמוד)', cardTitle: 'שם קצר לכרטיס', summary: 'תקציר', candidacy: 'למי מתאים', process: 'מהלך הטיפול', expect: 'למה לצפות', faq: 'שאלות על הטיפול', seoTitle: 'כותרת לגוגל (לא חובה)', seoDescription: 'תיאור קצר לגוגל', reviewedOn: 'תאריך בדיקה רפואית', step: 'שלב', detail: 'פירוט', q: 'שאלה', a: 'תשובה', slug: 'כתובת העמוד', status: 'מצב', icon: 'סמל' },
  errors: {
    AUTH_REQUIRED: 'החיבור למערכת פג. יש לרענן את הדף ולהתחבר שוב. השינויים שלא נשמרו יאבדו — כדאי להעתיק אותם קודם.',
    AUTH_INVALID: 'החיבור למערכת פג. יש לרענן את הדף ולהתחבר שוב.',
    FORBIDDEN: 'הפעולה נחסמה מטעמי אבטחה. יש לרענן את הדף ולנסות שוב.',
    NOT_FOUND: 'הפריט לא נמצא — ייתכן שנמחק. יש לטעון מחדש.',
    CONFLICT: 'התוכן השתנה מאז שנפתח (אולי בחלון או במכשיר אחר). כדי לא לדרוס שינוי, יש לטעון מחדש ולערוך שוב.',
    UPSTREAM_UNAVAILABLE: 'השמירה לא הצליחה — שירות האחסון לא זמין כרגע. השינויים עדיין כאן; נסו שוב בעוד רגע.',
    NOT_CONFIGURED: 'מערכת העריכה אינה מוגדרת כראוי. יש לפנות למפתח.',
    PAYLOAD_TOO_LARGE: 'הקובץ גדול מדי לשליחה.',
    RATE_LIMITED: 'נשלחו יותר מדי בקשות ברצף. המתינו כמה שניות ונסו שוב.',
    NETWORK: 'הבקשה לא הגיעה לשרת (בעיית חיבור, או תוסף בדפדפן שחוסם אותה). השינויים עדיין כאן; נסו שוב.',
    BAD_REQUEST: 'הבקשה לא תקינה. יש לרענן את הדף ולנסות שוב.',
    SERVER_ERROR: 'אירעה שגיאה בלתי צפויה. השינויים עדיין כאן; נסו שוב.',
    INVALID: 'לא נשמר. יש לתקן:',
  },
  issues: {
    confirmation_required: 'יש לאשר שבתמונה אין מטופל, חלק ממטופל או תמונת לפני/אחרי.',
    category_not_allowed: 'יש לבחור סוג תמונה מהרשימה.',
    alt_he_required: 'חסר תיאור בעברית.', alt_ar_required: 'חסר תיאור בערבית.', alt_en_required: 'חסר תיאור באנגלית.',
    alt_en_not_english: 'התיאור באנגלית צריך להיות כתוב באנגלית.',
    file_required: 'לא נבחר קובץ.', file_too_large: 'הקובץ גדול מ-8 מגה-בייט.',
    unsupported_format: 'הקובץ אינו תמונת JPG או PNG תקינה.', image_too_small: 'התמונה קטנה מדי — נדרשים לפחות 1200 פיקסלים בצד הארוך.',
    category_full: 'אין מקום לתמונות נוספות מסוג זה.', photo_not_actionable: 'לא ניתן לבצע את הפעולה על התמונה הזו. אם היא מוצגת באתר, יש להסתיר אותה קודם.',
    format_must_match: 'התמונה החדשה חייבת להיות באותו פורמט כמו הקודמת.',
    order_stale: 'רשימת התמונות השתנתה בינתיים. יש לטעון מחדש.', order_invalid: 'הסדר שנשלח לא תקין. יש לטעון מחדש.',
    owner_confirmation_required: 'יש לסמן את תיבת האישור שמתחת לטופס.',
    same_location_confirmation_required: 'שינוי כתובת דורש לסמן שזו אותה כתובת פיזית.',
    published_item_or_url_locked: 'אי אפשר למחוק פריט שמוצג באתר, או לשנות כתובת של טיפול שכבר נשמר. יש להסתיר אותו, לשמור, ורק אז למחוק.',
    content_invalid: 'התוכן אינו תקין.', wrong_row_count: 'רשימת הימים לא שלמה. יש לטעון מחדש.', not_an_array: 'רשימת הימים לא תקינה. יש לטעון מחדש.',
  },
  reasons: { too_small: 'חסר', too_big: 'ארוך מדי', invalid_format: 'בפורמט לא תקין', invalid_string: 'בפורמט לא תקין', invalid_type: 'חסר או לא תקין', custom: 'כפול — כבר קיים פריט עם אותה כתובת', invalid_union: 'לא תקין', invalid_union_discriminator: 'לא תקין', unrecognized_keys: 'מכיל שדה לא מוכר', invalid_value: 'לא תקין' },
};

const ar: Dict = {
  langName: 'العربية',
  close: 'إغلاق', save: 'حفظ', cancel: 'إلغاء', edit: 'تعديل', closeEdit: 'إغلاق التعديل', remove: 'إزالة', delete: 'حذف',
  up: 'لأعلى', down: 'لأسفل', upNamed: 'لأعلى: {name}', downNamed: 'لأسفل: {name}', named: '{action}: {name}', grip: 'سحب',
  published: 'معروض في الموقع', hidden: 'مخفي', publish: 'عرض في الموقع', unpublish: 'إخفاء من الموقع',
  warning: 'يُحفظ كل المحتوى في مستودع عام، حتى المحتوى المخفي. لا تُدخلوا معلومات عن المرضى أو تفاصيل طبية شخصية أو أسرارًا.',
  unsavedClose: 'هناك تغييرات غير محفوظة. هل تريد الإغلاق وفقدانها؟',
  unsavedSwitch: 'هناك تغييرات غير محفوظة. هل تريد الانتقال وفقدانها؟',
  unsavedReload: 'ستُفقد التغييرات غير المحفوظة. هل تريد إعادة التحميل؟',
  unsavedRefresh: 'هناك تغييرات غير محفوظة. هل تريد تحديث الصفحة رغم ذلك؟',
  loading: 'جارٍ تحميل المحتوى…', saving: 'جارٍ الحفظ…',
  nothingToSave: 'لا توجد تغييرات للحفظ — كل شيء محفوظ.',
  savedTest: 'تم الحفظ (commit {sha}، فرع تجريبي — الموقع العام لا يتغير).',
  savedProd: 'تم الحفظ (commit {sha})؛ لم يُنشر في الموقع بعد.',
  doneTest: '{what} (commit {sha}، فرع تجريبي).', doneProd: '{what} (commit {sha})؛ لم يُنشر في الموقع بعد.',
  noChange: 'لا يوجد تغيير للحفظ.',
  updating: 'جارٍ تحديث عرض الموقع…',
  updated: 'تم التحديث — جارٍ إعادة تحميل الصفحة…',
  updatedDirty: 'تم تحديث العرض. احفظوا التغييرات المفتوحة أو ألغوها، ثم حدّثوا الصفحة.',
  updatedAfterReload: 'تعرض الصفحة آخر تغيير تم حفظه.',
  refreshNow: 'تحديث الصفحة',
  updateFailed: 'تم حفظ التغيير، لكن تحديث عرض الموقع فشل. يمكن المحاولة مجددًا بحفظ آخر؛ وإذا تكرر ذلك، يرجى التواصل مع المطوّر.',
  updateNotConfigured: 'تم حفظ التغيير. التحديث التلقائي للعرض غير مُعدّ، لذلك ستعرضه الصفحة بعد إعادة البناء.',
  waitingPublish: 'تم الحفظ (commit {sha}). بانتظار النشر في الموقع…',
  publishedSite: 'نُشر في الموقع',
  publishFailed: 'تم الحفظ، لكن النشر فشل. يعرض الموقع النسخة السابقة. يرجى التواصل مع المطوّر.',
  testMode: 'وضع تجريبي: الحفظ لا يغيّر الموقع العام',
  claim: 'صياغة غير مسموح بها وفق قواعد الإعلان الطبي (مثل ضمان نتيجة أو "الأفضل")',
  moreIssues: 'قد توجد مشكلات أخرى؛ ستظهر بعد إصلاح هذه والحفظ مجددًا.',
  reloadLatest: 'إعادة تحميل أحدث محتوى', refreshSignIn: 'تحديث الصفحة وتسجيل الدخول',
  itemN: 'عنصر {n}', treatmentNamed: 'علاج "{name}"', questionNamed: 'سؤال "{name}"', field: 'حقل', invalidValue: 'قيمة غير صالحة.',
  dayLabel: 'يوم {day}', timesRequired: '{day}: يجب إدخال وقت الفتح ووقت الإغلاق (أو اختيار "مغلق").',
  opensAfterCloses: '{day}: يجب أن يكون وقت الفتح قبل وقت الإغلاق.', badTime: '{day}: وقت غير صالح.', badDay: '{day}: قيمة غير صالحة.',
  altClaim: 'الوصف باللغة {lang} يحتوي على صياغة غير مسموح بها وفق قواعد الإعلان الطبي.',
  showAllTexts: 'عرض كل نصوص الموقع',
  intro: 'مقدمة', approach: 'نهج العيادة — سطر لكل نقطة', credentials: 'التعليم والشهادات — حقائق مؤكدة كتابيًا فقط',
  year: 'السنة (اختياري)', removeCredential: 'إزالة الشهادة', addCredential: 'إضافة شهادة',
  ownerConfirm: 'أؤكد أن جميع التفاصيل التي تم تغييرها هنا صحيحة.',
  contactHint: 'تغيير العنوان هنا مخصص لتصحيح صياغة المكان نفسه. إذا انتقلت العيادة، يجب تحديث الخريطة ورابط Waze أيضًا عن طريق المطوّر.',
  sameLocation: 'أؤكد أن هذا هو العنوان الفعلي نفسه، وأن الخريطة ورابط Waze ما زالا صحيحين.',
  hoursHint: 'لم تُحدد بعد ساعات لبعض الأيام، لذلك لا تظهر ساعات العمل في الموقع. يجب إدخال وقت الفتح والإغلاق لكل يوم، أو اختيار "مغلق في هذا اليوم"، ثم الحفظ.',
  closedToday: 'مغلق في هذا اليوم', opens: 'الفتح', closes: 'الإغلاق',
  newTreatment: 'علاج جديد', addTreatment: '+ إضافة علاج', editTreatment: 'تعديل العلاج',
  servicesHint: 'الترتيب هنا هو الترتيب في الموقع. يمكن سحب العلاج من المقبض، أو استخدام زرّي لأعلى/لأسفل. تُحفظ التغييرات عند الضغط على "حفظ".',
  deleteItemConfirm: 'حذف "{name}"؟ سيتم الحذف عند الحفظ.', deleteNeedsSave: 'للحذف: يجب حفظ الإخفاء أولًا.',
  backToTreatments: '← العودة إلى قائمة العلاجات', editingTreatment: 'تعديل علاج: {name}',
  draftHint: 'مسودة: يمكن الحفظ حتى إن كانت بعض الحقول أو اللغات ناقصة. لعرضه في الموقع، يجب تعبئة كل الحقول باللغات الثلاث.',
  slugLabel: 'عنوان الصفحة بالإنجليزية (مثل dental-crowns). لا يمكن تغييره بعد الحفظ.', pageAddress: 'عنوان الصفحة: ',
  iconLabel: 'رمز', languageLabel: 'اللغة', addItem: 'إضافة عنصر',
  addQuestion: '+ إضافة سؤال', newQuestion: 'سؤال جديد', question: 'سؤال', answer: 'جواب',
  faqHint: 'يُحفظ السؤال الجديد مخفيًا. يمكن حفظ مسودة دون كل اللغات؛ لعرضه في الموقع يلزم نص بالعبرية والعربية والإنجليزية.',
  unsavedOrder: 'تغيير الترتيب لم يُحفظ بعد، وهذا الإجراء سيلغيه. هل تريد المتابعة؟',
  heic: 'صور HEIC من iPhone غير مدعومة. اختاروا الصورة من "الصور" (ستُحوَّل تلقائيًا إلى JPG)، أو احفظوها بصيغة JPG.',
  notJpgPng: '"{name}" ليس ملف JPG أو PNG.', unreadable: 'تعذّرت قراءة "{name}" كصورة.',
  tooSmall: '"{name}" صغيرة جدًا ({w}×{h}). يلزم {min} بكسل على الأقل في الضلع الأطول.', tooLargeAfter: '"{name}" كبيرة جدًا حتى بعد التصغير.',
  galleryCount: 'الصور في المعرض ({n})', galleryEmpty: 'لا توجد صور في المعرض بعد. يمكن إضافة صور في الأعلى.',
  galleryHint: 'تُحفظ الصورة الجديدة مخفية؛ تُعرض بزر "عرض في الموقع". الترتيب هنا هو الترتيب في الموقع — اسحبوا من المقبض أو استخدموا لأعلى/لأسفل، ثم "حفظ الترتيب".',
  orderChanged: 'تغيّر الترتيب ولم يُحفظ بعد.', saveOrder: 'حفظ الترتيب', savingOrder: 'جارٍ حفظ الترتيب…', orderSaved: 'تم حفظ الترتيب',
  needsEnglish: 'يلزم تأكيد الوصف بالإنجليزية', needEnglishFirst: 'يجب حفظ وصف بالإنجليزية أولًا', noPreview: 'تعذّر عرض المعاينة',
  editDescription: 'تعديل الوصف', closeDescription: 'إغلاق تعديل الوصف', descriptionGroup: 'وصف الصورة (لقارئات الشاشة ولـ Google)',
  saveDescription: 'حفظ الوصف', savingDescription: 'جارٍ حفظ الوصف…', descriptionSaved: 'تم حفظ الوصف',
  photoShown: 'تم تعيين الصورة للعرض في الموقع', photoHidden: 'تم إخفاء الصورة من الموقع',
  replace: 'استبدال الصورة', replaceConfirm: 'هل تؤكد أن الصورة الجديدة لا تُظهر مريضًا أو جزءًا من مريض أو صورة قبل/بعد؟',
  checkingImage: 'جارٍ فحص الصورة…', uploadingReplacement: 'جارٍ رفع الصورة الجديدة…', replaced: 'تم استبدال الصورة',
  deletePhotoConfirm: 'حذف الصورة "{name}" نهائيًا؟ يبقى السجل محفوظًا في المستودع.', deleting: 'جارٍ الحذف…', photoDeleted: 'تم حذف الصورة', hideFirst: 'للحذف يجب الإخفاء أولًا.',
  uploadGroup: 'إضافة صور إلى المعرض', dropHere: 'اسحبوا الصور إلى هنا، أو', choosePhotos: 'اختيار صور',
  uploadHint: 'JPG أو PNG، بحد أدنى 1200 بكسل في الضلع الأطول. تُصغَّر الصورة الكبيرة جدًا تلقائيًا.',
  previewOf: 'معاينة: {name}', uploading: 'جارٍ الرفع…', photoCategory: 'نوع الصورة', descriptionAll: 'وصف الصورة (مطلوب باللغات الثلاث)',
  removeFromList: 'إزالة من القائمة', uploadConfirm: 'أؤكد أن أيًّا من الصور لا تُظهر مريضًا أو جزءًا من مريض أو صورة قبل/بعد.',
  uploadOne: 'رفع صورة واحدة', uploadMany: 'رفع {n} صور', uploadingNofM: 'جارٍ رفع الصورة {n} من {m}…', uploadFailed: 'فشل الرفع.',
  uploadedOne: 'تم رفع الصورة وحفظها مخفية (commit {sha}). لعرضها في الموقع اضغطوا "عرض في الموقع".',
  uploadedMany: 'تم رفع {n} صور وحفظها مخفية (commit {sha}). لعرض صورة في الموقع اضغطوا "عرض في الموقع".',
  uploadedPartial: 'تم رفع {n} من {m}. {f} لم تُرفع — السبب يظهر بجانب كل صورة.',
  barTexts: 'كل النصوص', barTreatments: 'العلاجات', barPhotos: 'الصور', preview: 'عرض المريض', backToEdit: 'العودة إلى التعديل', exit: 'خروج',
  titles: { copy: 'نصوص الموقع', services: 'العلاجات', doctor: 'قسم الطبيب', faq: 'الأسئلة الشائعة', contact: 'بيانات الاتصال', hours: 'ساعات العمل', photos: 'معرض صور العيادة' },
  days: ['الأحد', 'الإثنين', 'الثلاثاء', 'الأربعاء', 'الخميس', 'الجمعة', 'السبت'],
  doctorParts: { intro: 'مقدمة', approach: 'نهج العيادة', credentials: 'التعليم والشهادات' },
  copyLabels: {
    'hero.eyebrow': 'سطر صغير فوق العنوان الرئيسي', 'hero.title': 'العنوان الرئيسي', 'hero.subtitle': 'الجملة الافتتاحية تحت العنوان',
    'trust.explanation.title': 'النقطة 1 — عنوان', 'trust.explanation.body': 'النقطة 1 — شرح', 'trust.languages.title': 'النقطة 2 — عنوان', 'trust.languages.body': 'النقطة 2 — شرح',
    'trust.availability.title': 'النقطة 3 — عنوان', 'trust.availability.body': 'النقطة 3 — شرح', 'trust.personal.title': 'النقطة 4 — عنوان', 'trust.personal.body': 'النقطة 4 — شرح',
    'treatments.title': 'عنوان قسم العلاجات', 'treatments.intro': 'مقدمة قسم العلاجات', 'doctor.title': 'عنوان قسم الطبيب', 'doctor.cta': 'زر قسم الطبيب', 'faq.title': 'عنوان الأسئلة الشائعة',
    'contact.title': 'عنوان صفحة التواصل', 'contact.subtitle': 'مقدمة صفحة التواصل', 'location.title': 'عنوان قسم الموقع', 'location.subtitle': 'مقدمة قسم الموقع',
    'gallery.eyebrow': 'سطر صغير فوق عنوان المعرض', 'gallery.title': 'عنوان المعرض', 'gallery.intro': 'مقدمة المعرض',
    'action.bookAppointment': 'زر حجز موعد', 'action.readMore': 'رابط "اقرأ المزيد"', 'action.allTreatments': 'رابط "كل العلاجات"',
    'feedback.title': 'عنوان قسم الملاحظات', 'feedback.body': 'نص قسم الملاحظات', 'feedback.cta': 'زر قسم الملاحظات',
  },
  contactLabels: { landline: 'هاتف أرضي (مثال 04-123-4567)', mobile: 'هاتف محمول (مثال 050-123-4567)', email: 'البريد الإلكتروني (اختياري)', postalCode: 'الرمز البريدي', instagram: 'رابط Instagram', facebook: 'رابط Facebook', googleBusiness: 'رابط ملف Google', street: 'الشارع والرقم', locality: 'البلدة', region: 'المنطقة' },
  categories: { exterior: 'واجهة العيادة', reception: 'الاستقبال والانتظار', 'treatment-room': 'غرفة العلاج', equipment: 'المعدات', 'doctor-working': 'الطبيب أثناء العمل', team: 'الطاقم', atmosphere: 'الأجواء' },
  icons: { implant: 'زرعة', crown: 'تاج', whitening: 'تبييض', filling: 'حشوة', veneer: 'قشرة', aligner: 'تقويم الأسنان', 'root-canal': 'علاج العصب', extraction: 'خلع', cleaning: 'تنظيف', emergency: 'طوارئ', aesthetic: 'تجميل' },
  serviceFields: { title: 'اسم العلاج (عنوان الصفحة)', cardTitle: 'اسم قصير للبطاقة', summary: 'ملخص', candidacy: 'لمن يناسب', process: 'مراحل العلاج', expect: 'ماذا تتوقع', faq: 'أسئلة عن العلاج', seoTitle: 'عنوان لـ Google (اختياري)', seoDescription: 'وصف قصير لـ Google', reviewedOn: 'تاريخ المراجعة الطبية', step: 'مرحلة', detail: 'تفصيل', q: 'سؤال', a: 'جواب', slug: 'عنوان الصفحة', status: 'الحالة', icon: 'رمز' },
  errors: {
    AUTH_REQUIRED: 'انتهت جلسة الدخول. يرجى تحديث الصفحة وتسجيل الدخول مجددًا. ستُفقد التغييرات غير المحفوظة — يُفضّل نسخها أولًا.',
    AUTH_INVALID: 'انتهت جلسة الدخول. يرجى تحديث الصفحة وتسجيل الدخول مجددًا.',
    FORBIDDEN: 'تم حظر الإجراء لأسباب أمنية. يرجى تحديث الصفحة والمحاولة مجددًا.',
    NOT_FOUND: 'العنصر غير موجود — ربما حُذف. يرجى إعادة التحميل.',
    CONFLICT: 'تغيّر المحتوى منذ فتحه (ربما في نافذة أو جهاز آخر). لتجنّب الكتابة فوق تغيير، يرجى إعادة التحميل والتعديل مجددًا.',
    UPSTREAM_UNAVAILABLE: 'لم ينجح الحفظ — خدمة التخزين غير متاحة حاليًا. التغييرات ما زالت هنا؛ حاولوا مجددًا بعد قليل.',
    NOT_CONFIGURED: 'نظام التعديل غير مُعدّ بشكل صحيح. يرجى التواصل مع المطوّر.',
    PAYLOAD_TOO_LARGE: 'الملف كبير جدًا للإرسال.',
    RATE_LIMITED: 'أُرسلت طلبات كثيرة متتالية. انتظروا بضع ثوانٍ وحاولوا مجددًا.',
    NETWORK: 'لم يصل الطلب إلى الخادم (مشكلة اتصال، أو إضافة في المتصفح تحجبه). التغييرات ما زالت هنا؛ حاولوا مجددًا.',
    BAD_REQUEST: 'الطلب غير صالح. يرجى تحديث الصفحة والمحاولة مجددًا.',
    SERVER_ERROR: 'حدث خطأ غير متوقع. التغييرات ما زالت هنا؛ حاولوا مجددًا.',
    INVALID: 'لم يُحفظ. يجب تصحيح:',
  },
  issues: {
    confirmation_required: 'يجب تأكيد أن الصورة لا تُظهر مريضًا أو جزءًا من مريض أو صورة قبل/بعد.',
    category_not_allowed: 'يجب اختيار نوع صورة من القائمة.',
    alt_he_required: 'الوصف بالعبرية ناقص.', alt_ar_required: 'الوصف بالعربية ناقص.', alt_en_required: 'الوصف بالإنجليزية ناقص.',
    alt_en_not_english: 'يجب أن يكون الوصف الإنجليزي مكتوبًا بالإنجليزية.',
    file_required: 'لم يتم اختيار ملف.', file_too_large: 'حجم الملف أكبر من 8 ميغابايت.',
    unsupported_format: 'الملف ليس صورة JPG أو PNG صالحة.', image_too_small: 'الصورة صغيرة جدًا — يلزم 1200 بكسل على الأقل في الضلع الأطول.',
    category_full: 'لا يوجد مكان لصور إضافية من هذا النوع.', photo_not_actionable: 'لا يمكن تنفيذ الإجراء على هذه الصورة. إذا كانت معروضة في الموقع، يجب إخفاؤها أولًا.',
    format_must_match: 'يجب أن تكون الصورة الجديدة بصيغة الصورة السابقة نفسها.',
    order_stale: 'تغيّرت قائمة الصور في هذه الأثناء. يرجى إعادة التحميل.', order_invalid: 'الترتيب المُرسل غير صالح. يرجى إعادة التحميل.',
    owner_confirmation_required: 'يجب تحديد مربع التأكيد أسفل النموذج.',
    same_location_confirmation_required: 'تغيير العنوان يتطلب تأكيد أنه العنوان الفعلي نفسه.',
    published_item_or_url_locked: 'لا يمكن حذف عنصر معروض في الموقع، أو تغيير عنوان علاج محفوظ. يجب إخفاؤه والحفظ، ثم الحذف.',
    content_invalid: 'المحتوى غير صالح.', wrong_row_count: 'قائمة الأيام غير مكتملة. يرجى إعادة التحميل.', not_an_array: 'قائمة الأيام غير صالحة. يرجى إعادة التحميل.',
  },
  reasons: { too_small: 'ناقص', too_big: 'طويل جدًا', invalid_format: 'بصيغة غير صالحة', invalid_string: 'بصيغة غير صالحة', invalid_type: 'ناقص أو غير صالح', custom: 'مكرر — يوجد عنصر بالعنوان نفسه', invalid_union: 'غير صالح', invalid_union_discriminator: 'غير صالح', unrecognized_keys: 'يحتوي على حقل غير معروف', invalid_value: 'غير صالح' },
};

const en: Dict = {
  langName: 'English',
  close: 'Close', save: 'Save', cancel: 'Cancel', edit: 'Edit', closeEdit: 'Close editing', remove: 'Remove', delete: 'Delete',
  up: 'Move up', down: 'Move down', upNamed: 'Move up: {name}', downNamed: 'Move down: {name}', named: '{action}: {name}', grip: 'Drag',
  published: 'Shown on site', hidden: 'Hidden', publish: 'Show on site', unpublish: 'Hide from site',
  warning: 'Everything is saved in a public repository, including hidden content. Do not enter patient information, personal medical details or secrets.',
  unsavedClose: 'You have unsaved changes. Close and lose them?',
  unsavedSwitch: 'You have unsaved changes. Switch and lose them?',
  unsavedReload: 'Unsaved changes will be lost. Reload?',
  unsavedRefresh: 'You have unsaved changes. Refresh anyway?',
  loading: 'Loading content…', saving: 'Saving…',
  nothingToSave: 'Nothing to save — everything is already saved.',
  savedTest: 'Saved (commit {sha}, test branch — the public site does not change).',
  savedProd: 'Saved (commit {sha}); not yet published on the site.',
  doneTest: '{what} (commit {sha}, test branch).', doneProd: '{what} (commit {sha}); not yet published on the site.',
  noChange: 'Nothing to save.',
  updating: 'Updating the website view…',
  updated: 'Updated — reloading the page…',
  updatedDirty: 'The view is updated. Save or discard your open changes, then refresh.',
  updatedAfterReload: 'This page shows your latest saved change.',
  refreshNow: 'Refresh the page',
  updateFailed: 'Your change is saved, but updating the website view failed. Saving again retries it; if it keeps failing, contact the developer.',
  updateNotConfigured: 'Your change is saved. Automatic view updates are not set up, so the page will show it after a rebuild.',
  waitingPublish: 'Saved (commit {sha}). Waiting to be published on the site…',
  publishedSite: 'Published on the site',
  publishFailed: 'Saved, but publishing failed. The site still shows the previous version. Please contact the developer.',
  testMode: 'Test mode: saving does not change the public site',
  claim: 'wording not allowed under medical advertising rules (for example promising a result, or "the best")',
  moreIssues: 'There may be more; they will appear after you fix these and save again.',
  reloadLatest: 'Reload the latest content', refreshSignIn: 'Refresh the page and sign in',
  itemN: 'Item {n}', treatmentNamed: 'Treatment "{name}"', questionNamed: 'Question "{name}"', field: 'Field', invalidValue: 'Invalid value.',
  dayLabel: '{day}', timesRequired: '{day}: enter opening and closing times (or mark it "Closed").',
  opensAfterCloses: '{day}: opening time must be before closing time.', badTime: '{day}: invalid time.', badDay: '{day}: invalid value.',
  altClaim: 'The {lang} description contains wording not allowed under medical advertising rules.',
  showAllTexts: 'Show all site texts',
  intro: 'Introduction', approach: 'Clinic approach — one line per point', credentials: 'Education and qualifications — confirmed facts only',
  year: 'Year (optional)', removeCredential: 'Remove qualification', addCredential: 'Add qualification',
  ownerConfirm: 'I confirm that every detail changed here is correct.',
  contactHint: 'Changing the address here is for correcting the wording of the same place. If the clinic has moved, the map and Waze link must also be updated by the developer.',
  sameLocation: 'I confirm this is the same physical address, and the map and Waze link are still correct.',
  hoursHint: 'Some days have no hours yet, so opening hours are not shown on the site. Enter opening and closing times for every day, or mark it "Closed on this day", then save.',
  closedToday: 'Closed on this day', opens: 'Opens', closes: 'Closes',
  newTreatment: 'New treatment', addTreatment: '+ Add treatment', editTreatment: 'Edit treatment',
  servicesHint: 'The order here is the order on the site. Drag a treatment by its handle, or use Move up/Move down. Changes are saved when you press "Save".',
  deleteItemConfirm: 'Delete "{name}"? It is deleted when you save.', deleteNeedsSave: 'To delete: save the hiding first.',
  backToTreatments: '← Back to the treatments list', editingTreatment: 'Editing treatment: {name}',
  draftHint: 'Draft: you can save even when some fields or languages are missing. To show it on the site, fill in every field in all three languages.',
  slugLabel: 'Page address in English (for example dental-crowns). It cannot be changed after saving.', pageAddress: 'Page address: ',
  iconLabel: 'Icon', languageLabel: 'Language', addItem: 'Add item',
  addQuestion: '+ Add question', newQuestion: 'New question', question: 'Question', answer: 'Answer',
  faqHint: 'A new question is saved hidden. You can save a draft without every language; showing it on the site requires Hebrew, Arabic and English.',
  unsavedOrder: 'The new order is not saved yet, and this action will discard it. Continue?',
  heic: 'iPhone HEIC photos are not supported. Pick the photo from "Photos" (it converts to JPG automatically), or save it as JPG.',
  notJpgPng: '"{name}" is not a JPG or PNG file.', unreadable: '"{name}" could not be read as an image.',
  tooSmall: '"{name}" is too small ({w}×{h}). At least {min} pixels are needed on the long side.', tooLargeAfter: '"{name}" is too large even after resizing.',
  galleryCount: 'Photos in the gallery ({n})', galleryEmpty: 'There are no photos in the gallery yet. Add photos above.',
  galleryHint: 'A new photo is saved hidden; show it with "Show on site". The order here is the order on the site — drag by the handle or use Move up/Move down, then "Save order".',
  orderChanged: 'The order has changed and is not saved yet.', saveOrder: 'Save order', savingOrder: 'Saving the order…', orderSaved: 'Order saved',
  needsEnglish: 'English description needs confirming', needEnglishFirst: 'Save an English description first', noPreview: 'Preview unavailable',
  editDescription: 'Edit description', closeDescription: 'Close description', descriptionGroup: 'Photo description (for screen readers and Google)',
  saveDescription: 'Save description', savingDescription: 'Saving description…', descriptionSaved: 'Description saved',
  photoShown: 'Photo set to show on the site', photoHidden: 'Photo hidden from the site',
  replace: 'Replace photo', replaceConfirm: 'Confirm the new photo shows no patient, part of a patient, or before/after image?',
  checkingImage: 'Checking the photo…', uploadingReplacement: 'Uploading the new photo…', replaced: 'Photo replaced',
  deletePhotoConfirm: 'Permanently delete the photo "{name}"? The history stays in the repository.', deleting: 'Deleting…', photoDeleted: 'Photo deleted', hideFirst: 'Hide it first to delete it.',
  uploadGroup: 'Add photos to the gallery', dropHere: 'Drop photos here, or', choosePhotos: 'Choose photos',
  uploadHint: 'JPG or PNG, at least 1200 pixels on the long side. Photos that are too large are resized automatically.',
  previewOf: 'Preview: {name}', uploading: 'Uploading…', photoCategory: 'Photo type', descriptionAll: 'Photo description (required in all three languages)',
  removeFromList: 'Remove from list', uploadConfirm: 'I confirm none of these photos shows a patient, part of a patient, or a before/after image.',
  uploadOne: 'Upload 1 photo', uploadMany: 'Upload {n} photos', uploadingNofM: 'Uploading photo {n} of {m}…', uploadFailed: 'Upload failed.',
  uploadedOne: 'The photo was uploaded and saved hidden (commit {sha}). To show it on the site, press "Show on site".',
  uploadedMany: '{n} photos were uploaded and saved hidden (commit {sha}). To show a photo on the site, press "Show on site".',
  uploadedPartial: 'Uploaded {n} of {m}. {f} failed — the reason is shown next to each photo.',
  barTexts: 'All texts', barTreatments: 'Treatments', barPhotos: 'Photos', preview: 'Patient view', backToEdit: 'Back to editing', exit: 'Exit',
  titles: { copy: 'Site texts', services: 'Treatments', doctor: 'Doctor section', faq: 'FAQ', contact: 'Contact details', hours: 'Opening hours', photos: 'Clinic photo gallery' },
  days: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
  doctorParts: { intro: 'Introduction', approach: 'Clinic approach', credentials: 'Education and qualifications' },
  copyLabels: {
    'hero.eyebrow': 'Small line above the main heading', 'hero.title': 'Main heading', 'hero.subtitle': 'Opening sentence under the heading',
    'trust.explanation.title': 'Point 1 — title', 'trust.explanation.body': 'Point 1 — text', 'trust.languages.title': 'Point 2 — title', 'trust.languages.body': 'Point 2 — text',
    'trust.availability.title': 'Point 3 — title', 'trust.availability.body': 'Point 3 — text', 'trust.personal.title': 'Point 4 — title', 'trust.personal.body': 'Point 4 — text',
    'treatments.title': 'Treatments section heading', 'treatments.intro': 'Treatments section intro', 'doctor.title': 'Doctor section heading', 'doctor.cta': 'Doctor section button', 'faq.title': 'FAQ heading',
    'contact.title': 'Contact page heading', 'contact.subtitle': 'Contact page intro', 'location.title': 'Location section heading', 'location.subtitle': 'Location section intro',
    'gallery.eyebrow': 'Small line above the gallery heading', 'gallery.title': 'Gallery heading', 'gallery.intro': 'Gallery intro',
    'action.bookAppointment': 'Book appointment button', 'action.readMore': '"Read more" link', 'action.allTreatments': '"All treatments" link',
    'feedback.title': 'Feedback section heading', 'feedback.body': 'Feedback section text', 'feedback.cta': 'Feedback section button',
  },
  contactLabels: { landline: 'Landline (for example 04-123-4567)', mobile: 'Mobile (for example 050-123-4567)', email: 'Email (optional)', postalCode: 'Postal code', instagram: 'Instagram link', facebook: 'Facebook link', googleBusiness: 'Google profile link', street: 'Street and number', locality: 'Town', region: 'Region' },
  categories: { exterior: 'Clinic exterior', reception: 'Reception and waiting', 'treatment-room': 'Treatment room', equipment: 'Equipment', 'doctor-working': 'Doctor at work', team: 'Team', atmosphere: 'Atmosphere' },
  icons: { implant: 'Implant', crown: 'Crown', whitening: 'Whitening', filling: 'Filling', veneer: 'Veneer', aligner: 'Aligners', 'root-canal': 'Root canal', extraction: 'Extraction', cleaning: 'Cleaning', emergency: 'Emergency', aesthetic: 'Aesthetic' },
  serviceFields: { title: 'Treatment name (page heading)', cardTitle: 'Short name for the card', summary: 'Summary', candidacy: 'Who it suits', process: 'Treatment steps', expect: 'What to expect', faq: 'Questions about the treatment', seoTitle: 'Title for Google (optional)', seoDescription: 'Short description for Google', reviewedOn: 'Medical review date', step: 'Step', detail: 'Detail', q: 'Question', a: 'Answer', slug: 'Page address', status: 'Status', icon: 'Icon' },
  errors: {
    AUTH_REQUIRED: 'Your sign-in has expired. Refresh the page and sign in again. Unsaved changes will be lost — copy them first.',
    AUTH_INVALID: 'Your sign-in has expired. Refresh the page and sign in again.',
    FORBIDDEN: 'The action was blocked for security reasons. Refresh the page and try again.',
    NOT_FOUND: 'The item was not found — it may have been deleted. Reload.',
    CONFLICT: 'The content changed since you opened it (perhaps in another window or device). To avoid overwriting a change, reload and edit again.',
    UPSTREAM_UNAVAILABLE: 'Saving failed — the storage service is unavailable right now. Your changes are still here; try again in a moment.',
    NOT_CONFIGURED: 'The editing system is not configured correctly. Please contact the developer.',
    PAYLOAD_TOO_LARGE: 'The file is too large to send.',
    RATE_LIMITED: 'Too many requests in a row. Wait a few seconds and try again.',
    NETWORK: 'The request did not reach the server (a connection problem, or a browser extension blocking it). Your changes are still here; try again.',
    BAD_REQUEST: 'The request was not valid. Refresh the page and try again.',
    SERVER_ERROR: 'Something unexpected went wrong. Your changes are still here; try again.',
    INVALID: 'Not saved. Please fix:',
  },
  issues: {
    confirmation_required: 'Confirm the photo shows no patient, part of a patient, or before/after image.',
    category_not_allowed: 'Choose a photo type from the list.',
    alt_he_required: 'The Hebrew description is missing.', alt_ar_required: 'The Arabic description is missing.', alt_en_required: 'The English description is missing.',
    alt_en_not_english: 'The English description must be written in English.',
    file_required: 'No file was chosen.', file_too_large: 'The file is larger than 8 MB.',
    unsupported_format: 'The file is not a valid JPG or PNG image.', image_too_small: 'The image is too small — at least 1200 pixels are needed on the long side.',
    category_full: 'There is no room for more photos of this type.', photo_not_actionable: 'This action cannot be done on this photo. If it is shown on the site, hide it first.',
    format_must_match: 'The new photo must be in the same format as the previous one.',
    order_stale: 'The photo list changed in the meantime. Reload.', order_invalid: 'The order sent was not valid. Reload.',
    owner_confirmation_required: 'Tick the confirmation box below the form.',
    same_location_confirmation_required: 'Changing the address requires confirming it is the same physical address.',
    published_item_or_url_locked: 'An item shown on the site cannot be deleted, and a saved treatment’s address cannot change. Hide it, save, then delete.',
    content_invalid: 'The content is not valid.', wrong_row_count: 'The list of days is incomplete. Reload.', not_an_array: 'The list of days is not valid. Reload.',
  },
  reasons: { too_small: 'missing', too_big: 'too long', invalid_format: 'in an invalid format', invalid_string: 'in an invalid format', invalid_type: 'missing or invalid', custom: 'a duplicate — an item with the same address exists', invalid_union: 'invalid', invalid_union_discriminator: 'invalid', unrecognized_keys: 'contains an unknown field', invalid_value: 'invalid' },
};

export const EDITOR_STRINGS = { he, ar, en } as const;
